apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: fluentbit
  name: fluentbit
spec:
  template:
    metadata:
      labels:
        app: fluentbit
    spec:
      containers:
        - name: fluentbit
          image: allamagoosa/fluentbit:test
          volumeMounts:
          - name: var-lib-containers
            mountPath: /var/lib/docker/containers/
            readOnly: true
      volumes:
      - name: var-lib-containers
        hostPath:
          path: /var/lib/docker/containers/
